### PR TITLE
[Merged by Bors] - feat: add button instructions to player select menu.

### PR DESCRIPTION
**Pull request by lecoqjacob**

### CODE REVIEW

**Comment by lecoqjacob** [comment]
https://user-images.githubusercontent.com/9278174/213548496-a018b905-3863-4f64-b176-7bde1649332c.mp4

**Comment by lecoqjacob** [comment]
Added gamepad support

image

**Comment by zicklag** [comment]
One more thought: would it be easy to show something like "Press Space / South to join" for players 1 and 2, because the first two gamepads will actually control players one and two?

**Comment by lecoqjacob** [comment]
https://user-images.githubusercontent.com/9278174/213593099-5bafe3b9-ffb8-4d70-acd9-ba334e71c31d.mp4

**Review by zicklag — APPROVED** [review]
Awesome!

bors merge

**Pull request closed without merging**
