### PR TITLE
matchmaker: switch postcard dependency from crate to git

### PR DESCRIPTION
**Pull request by figsoda**
otherwise `cargo vendor` fails

### CODE REVIEW

**Comment by zicklag** [comment]
Thank you! Would you mind updating the postcard version in the main `jumpy` `Cargo.toml`, too?

The fork that it was pointing to had a useful feature for custom error messages, but since we're not messing much with custom serialization, it's not super important right now.

**Comment by zicklag** [comment]
bors merge

**Comment by figsoda** [comment]
Thanks! Do you mind creating a new version? I'm trying to package this for nixpkgs and it would be nice to use this without a patch

**Comment by zicklag** [comment]
Ah, I was wondering what you were vendoring the deps for. :) Cool!

You don't need a crates.io release right?

**Comment by figsoda** [comment]
yep just a tag on github is good enough

**Comment by zicklag** [comment]
Sure, I can make a patch release in just a minute.

FYI there's a Docker container for running the matchmaking server if you use Docker, too. Just mentioning it because I didn't put it in the README or anything.

**Comment by figsoda** [comment]
By the way, I meant to say the version of jumpy

**Comment by zicklag** [comment]
Sorry for the delay, I had a temporary network outage due to weather and I didn't get the chance to come push the tag until now.

You should now be able to use the `v0.5.1` tag.

**Comment by zicklag** [comment]
Whoops, I'm pulling the tag down just a second and I'll push it again after https://github.com/fishfolk/jumpy/pull/526 finishes. The lockfile is out of date.

**Comment by zicklag** [comment]
OK, fixed it and re-pushed the tag.

**Comment by figsoda** [comment]
thanks!

**Pull request merged**
