### PR TITLE
[Merged by Bors] - feat: re-add camera shake to items.

### PR DESCRIPTION
**Pull request by DRuppFv**
_ _ _
After this, I'll make a major PR, I just need this to be merged first.

### CODE REVIEW

**Review by zicklag — APPROVED** [review]
Thanks! This looks good. I merged https://github.com/fishfolk/bones/pull/104 into bones first, and I'm pushing up my tweaks to the camera shake parameters.

Also I'm removing the camera shake on the crate for now. During testing, me and @TekhnaeRaav felt that the crate doesn't feel right shaking the ground like an explosion would.

We can tweak the prarameters more, too, if we get feedback saying it doesn't feel right.

bors merge

**Comment by DRuppFv** [comment]
> Thanks! This looks good. I merged [fishfolk/bones#104](https://github.com/fishfolk/bones/pull/104) into bones first, and I'm pushing up my tweaks to the camera shake parameters.
> 
> Also I'm removing the camera shake on the crate for now. During testing, me and @TekhnaeRaav felt that the crate doesn't feel right shaking the ground like an explosion would.
> 
> We can tweak the prarameters more, too, if we get feedback saying it doesn't feel right.
> 
> bors merge

Ok. I've been thinking of adding camera shake on the musket (only to the shooter), but this answer made me wonder if you would use this. What do you think?

**Comment by zicklag** [comment]
Yeah, I'm thinking we probably don't want to add camera shake to the musket, but I can only speak for me and @TekhnaeRaav. It seems best to me to keep it to explosions for now.

@erlend-sh or @legendiguess do you have any thoughts?

**Comment by erlend-sh** [comment]
Yeah during initial testing we were fine with applying the shale more liberally, but it should really just be used for explosions and other high impact weapons.

**Pull request closed without merging**
